try{
if(typeof TREND_HISTORY==='undefined'||!Array.isArray(TREND_HISTORY)||!TREND_HISTORY.length)throw new Error('Trend history is missing or empty. Place the generated data.js beside trends.html.');
const el=id=>document.getElementById(id), esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const districts=[...new Set(TREND_HISTORY.flatMap(h=>h.units.map(u=>u.district)))].sort();let sort='delta',ascending=false,exportRows=[];
const fmt=(v,p=false)=>v==null?'—':p?v.toFixed(1)+'%':v.toLocaleString('en-US'),delta=(a,b,p=false)=>a==null||b==null?'—':(b-a>0?'+':'')+fmt(b-a,p)+(p?' pts':'');
const sum=(us,k)=>us.some(u=>u[k]!=null)?us.reduce((a,u)=>a+(u[k]??0),0):null,ratio=(a,b)=>a==null||!b?null:100*a/b;
function scoped(h,d=el('district').value,u=el('unit').value){return h.units.filter(x=>(!d||x.district===d)&&(!u||x.id===u))}
function totals(h,d=el('district').value,u=el('unit').value){const us=scoped(h,d,u);return {youth:sum(us,'youth'),adults:u?us[0]?.adults??null:d?h.adults.byDistrict[d]??null:h.adults.council,units:us.length,training:ratio(sum(us,'trained'),sum(us,'leaders')),syt:ratio(sum(us,'sytCurrent'),sum(us,'sytTotal')),metrics:ratio(sum(us,'score'),us.filter(x=>x.score!=null).length*5),yoy:sum(us,'yoy'),retention:u?us[0]?.retention??null:null}}
function table(head,rows){return '<table><thead><tr>'+head.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
function units(){let old=el('unit').value;el('unit').innerHTML='<option value="">All Units</option>'+[...new Map(TREND_HISTORY.flatMap(h=>scoped(h,el('district').value,'').map(u=>[u.id,u]))).values()].sort((a,b)=>a.label.localeCompare(b.label,undefined,{numeric:true})).map(u=>`<option value="${esc(u.id)}">${esc(u.label+' · '+u.district)}</option>`).join('');if([...el('unit').options].some(o=>o.value===old))el('unit').value=old}
function chart(title,key,hs,pct){const vals=hs.map(h=>totals(h)[key]),valid=vals.filter(v=>v!=null);if(!valid.length)return `<div class="panel"><h2>${title}</h2><p>No data available</p></div>`;let lo=pct?0:Math.max(0,Math.min(...valid)-10),hi=pct?100:Math.max(...valid)+10;if(hi===lo)hi++;let points=vals.map((v,i)=>v==null?null:[60+i*480/Math.max(1,hs.length-1),200-150*(v-lo)/(hi-lo)]);return `<div class="panel"><h2>${title}</h2><svg viewBox="0 0 600 250" role="img" aria-label="${title}"><path d="M60 30V200H550" fill="none" stroke="var(--line)"/><text x="5" y="40" fill="var(--muted)" font-size="12">${fmt(hi,pct)}</text><text x="5" y="200" fill="var(--muted)" font-size="12">${fmt(lo,pct)}</text>${points.map((pt,i)=>pt?`${i&&points[i-1]?`<line x1="${points[i-1][0]}" y1="${points[i-1][1]}" x2="${pt[0]}" y2="${pt[1]}" stroke="#64b9ef" stroke-width="3"/>`:''}<circle cx="${pt[0]}" cy="${pt[1]}" r="5" fill="#40bd95"><title>${hs[i].date}: ${fmt(vals[i],pct)}</title></circle><text x="${pt[0]}" y="${pt[1]-12}" text-anchor="middle" fill="var(--text)" font-size="13">${fmt(vals[i],pct)}</text>`:'').join('')}${hs.map((h,i)=>`<text x="${60+i*480/Math.max(1,hs.length-1)}" y="230" text-anchor="middle" fill="var(--muted)" font-size="12">${h.date.slice(5)}</text>`).join('')}</svg></div>`}
function render(){let a=Number(el('start').value),b=Number(el('end').value);if(a>b){b=a;el('end').value=b}let hs=TREND_HISTORY.slice(a,b+1),first=hs[0],last=hs.at(-1),t=totals(last),prev=totals(hs.length>1?hs.at(-2):first),base=totals(first);el('range').textContent=`${first.date} → ${last.date} · ${hs.length} snapshots · Latest source: ${last.generatedAt}`;
let au=scoped(first),bu=scoped(last),am=new Map(au.map(u=>[u.id,u])),bm=new Map(bu.map(u=>[u.id,u])),common=bu.filter(u=>am.has(u.id)),added=bu.filter(u=>!am.has(u.id)),removed=au.filter(u=>!bm.has(u.id)),growth=common.filter(u=>u.youth>am.get(u.id).youth).length,loss=common.filter(u=>u.youth<am.get(u.id).youth).length;
let cards=[['Youth membership','youth',false],['Adult membership','adults',false],['Units in snapshot','units',false],['Direct-contact training','training',true],['SYT current','syt',true],['Unit Metrics met','metrics',true],['Growing units',null,false,growth],['Declining units',null,false,loss]];el('cards').innerHTML=cards.map(([label,k,p,v])=>`<div class="panel"><small>${label}</small><div class="value">${fmt(k?t[k]:v,p)}</div><small>${k?'<span class="change-pill '+(t[k]>prev[k]?'good':t[k]<prev[k]?'bad':'')+'">'+delta(prev[k],t[k],p)+'</span> since previous snapshot':'Among comparable units'}</small></div>`).join('');let matched=common.reduce((n,u)=>n+u.youth-am.get(u.id).youth,0);el('context').innerHTML=`<b>${esc(el('unit').value?bu[0]?.label||au[0]?.label:el('district').value||'Northern Lights District')}</b> · Youth change ${delta(base.youth,t.youth)} from baseline.<br>Comparable units: ${common.length} · Change within these units: ${matched>=0?'+':''}${matched}. Added to dataset: ${added.length} (${sum(added,'youth')??0} youth). Removed: ${removed.length} (${sum(removed,'youth')??0} youth).<br><small>Dataset additions and removals are shown separately. Preliminary trends across ${hs.length} snapshot(s).</small>`;
const change=base.youth==null||t.youth==null?null:t.youth-base.youth,changePct=base.youth?100*change/base.youth:null;el('insights').innerHTML=`<div class="insight"><b>Membership momentum</b><p><strong>${delta(base.youth,t.youth)} youth${changePct==null?'':' ('+(changePct>0?'+':'')+fmt(changePct,true)+')'}</strong> across the selected period. ${growth} comparable units gained youth; ${loss} lost youth.</p></div><div class="insight"><b>Training movement</b><p><strong>${delta(base.training,t.training,true)}</strong> in direct-contact training, from ${fmt(base.training,true)} to ${fmt(t.training,true)}.</p></div><div class="insight"><b>Unit Metrics movement</b><p><strong>${delta(base.metrics,t.metrics,true)}</strong> in metrics attainment. ${added.length} added and ${removed.length} removed dataset units may affect the aggregate.</p></div>`;
el('charts').innerHTML=[['Youth membership','youth',false],['Adult membership','adults',false],['Direct-contact training','training',true],['Unit Metrics attainment','metrics',true],['SYT current','syt',true]].map(x=>chart(...x.slice(0,2),hs,x[2])).join('');
el('districtTable').innerHTML=table(['District','Youth baseline','Youth latest','Change','Adults latest','Training latest'],districts.map(d=>{let x=totals(first,d,''),y=totals(last,d,'');return [`<button data-district="${esc(d)}">${esc(d)}</button>`,fmt(x.youth),fmt(y.youth),delta(x.youth,y.youth),fmt(y.adults),fmt(y.training,true)]}));
let rows=[...new Set([...am.keys(),...bm.keys()])].map(id=>{let x=am.get(id),y=bm.get(id);return {id,label:(y||x).label,district:(y||x).district,before:x?.youth??null,after:y?.youth??null,delta:x&&y?y.youth-x.youth:null,score:y?.score??null,metricDelta:x&&y?y.score-x.score:null,training:y?ratio(y.trained,y.leaders):null,contact:y?.contact,status:!x?'Added to dataset':!y?'Removed from dataset':y.score>x.score?'Improving':y.score<x.score?'Declining':'Stable',health:y?(y.score>=4?'Green':y.score>=2?'Yellow':'Red'):'—'}}).filter(r=>(r.label+' '+r.district).toLowerCase().includes(el('search').value.toLowerCase()));rows.sort((x,y)=>{let v=typeof x[sort]==='string'?x[sort].localeCompare(y[sort]):(x[sort]??-Infinity)-(y[sort]??-Infinity);return ascending?v:-v});exportRows=rows;
let headers=[['Unit','label'],['District','district'],['Youth baseline','before'],['Youth latest','after'],['Youth change','delta'],['Metrics status','score'],['Metrics movement','metricDelta'],['Training latest','training'],['Last connection','contact']];el('movers').innerHTML=table(headers.map(([l,k])=>`<button data-sort="${k}">${l} ↕</button>`),rows.map(r=>[`<button data-unit="${esc(r.id)}">${esc(r.label)}</button>`,esc(r.district),fmt(r.before),fmt(r.after),r.delta==null?'—':delta(0,r.delta),`${r.health} (${fmt(r.score)}/5)`,esc(r.status)+(r.metricDelta==null?'':' · '+delta(0,r.metricDelta)),fmt(r.training,true),esc(r.contact)]));
el('history').innerHTML=table(['Snapshot','Youth','Adults','Units','Training','SYT current','Metrics met','YOY youth difference',...(el('unit').value?['Retention','Last connection','Renewal','Charter expiry']:[])],hs.map(h=>{let v=totals(h),u=scoped(h)[0];return [h.date,fmt(v.youth),fmt(v.adults),fmt(v.units),fmt(v.training,true),fmt(v.syt,true),fmt(v.metrics,true),fmt(v.yoy),...(el('unit').value?[fmt(v.retention,true),esc(u?.contact),esc(u?.renewal),esc(u?.expiry)]:[])]}));}
el('district').innerHTML+=districts.map(d=>`<option>${esc(d)}</option>`).join('');for(let id of ['start','end'])el(id).innerHTML=TREND_HISTORY.map((h,i)=>`<option value="${i}">${h.date}</option>`).join('');el('start').value='0';el('end').value=TREND_HISTORY.length-1;units();el('district').onchange=()=>{el('unit').value='';units();render()};for(let id of ['unit','start','end'])el(id).onchange=render;el('search').oninput=render;el('theme').onclick=()=>{document.body.classList.toggle('light');try{localStorage.setItem('trend-theme',document.body.className)}catch(e){}};try{document.body.className=localStorage.getItem('trend-theme')||''}catch(e){document.body.className=''};
document.onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.unit){el('unit').value=b.dataset.unit;render();scrollTo({top:0,behavior:'smooth'})}if(b.dataset.district){el('district').value=b.dataset.district;el('unit').value='';units();render()}if(b.dataset.sort){ascending=sort===b.dataset.sort?!ascending:false;sort=b.dataset.sort;render()}};
el('export').onclick=()=>{const ks=['label','district','before','after','delta','score','status','training','contact'];let csv=[ks,...exportRows.map(r=>ks.map(k=>r[k]??''))].map(r=>r.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\r\n'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='northern-lights-trend-comparison.csv';a.click();URL.revokeObjectURL(url)};render();

}catch(error){document.getElementById('range').textContent='Trends could not load: '+error.message;console.error(error);}
